name: build snapshot

on:
  workflow_call:
    inputs:
      namespace:
        required: false
        type: string
        default: '@rush-monorepo-boilerplate'
      namespace:
        required: false
        type: string
        default: '@rush-monorepo-boilerplate'
      package-name:
        required: false
        type: string
      package-path:
        required: false
        type: string
        default: './packages'
      lcov:
        required: false
        type: boolean
        default: false
      storybook:
        required: false
        type: boolean
        default: false
      build:
        required: false
        type: boolean
        default: true
jobs:
  build-package:
    # Operating system to run job on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3
      # setup
      - uses: ./.github/actions/setup
      # Run rush install
      - name: Install dependencies
        continue-on-error: true
        run: |
          node common/scripts/install-run-rush.js change -v
          node common/scripts/install-run-rush.js install
      # Run lint for this package
      - name: lint ${{ inputs.package-name }}
        if: inputs.package-name != ''
        run: node common/scripts/install-run-rush.js lint --to ${{ inputs.namespace }}/${{ inputs.package-name }}
        continue-on-error: true
      # Run unit tests for this package
      - name: test ${{ inputs.package-name }}
        if: inputs.package-name != '' && inputs.lcov == ''
        run: node common/scripts/install-run-rush.js test --to ${{ inputs.namespace }}/${{ inputs.package-name }}
      - name: test:lcov ${{ inputs.package-name }}
        if: inputs.lcov != ''
        working-directory: ${{ inputs.package-path }}/${{ inputs.package-name }}
        run: |
          echo - ${{ inputs.package-path }} - ${{ inputs.package-name }} - ${{ github.job }}
          node $GITHUB_WORKSPACE/common/scripts/install-run-rushx.js coverage
      - name: Coveralls GitHub Action
        if: inputs.lcov != ''
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          file: ${{ github.workspace }}/${{ inputs.package-path }}/${{ inputs.package-name }}/coverage/lcov.info
          format: lcov
          flag-name: ${{ inputs.package-name }}
          parallel: true
      - name: build ${{ inputs.package-name }}
        if: ${{ inputs.build }}
        working-directory: ${{ inputs.package-path }}/${{ inputs.package-name }}
        run: |
          node $GITHUB_WORKSPACE/common/scripts/install-run-rush.js build --verbose --to ${{ inputs.namespace }}/${{ inputs.package-name }}
    continue-on-error: true