name: build snapshot

on:
  push:
  pull_request:
jobs:
  base:
    uses: ./.github/workflows/base.yml
    with:
      build: false
      lcov: false
      storybook: false
  app-1:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: "@rush-monorepo-boilerplate/app-1" 
      storybook: true
      lcov: true
  eslint-config-react:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: "@fieryeagle/eslint-config-react"
      lcov: true
  measure-hook:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: measure-hook
      lcov: true
      build: false
  pkce:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: '@fieryeagle/pkce'
      lcov: true
  finish:
    needs: [app-1,eslint-config-react,measure-hook,pkce]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "app-1,eslint-config-react,measure-hook,pkce"
    continue-on-error: true