name: build snapshot

on:
  push:
  pull_request:
jobs:
  base:
    uses: ./.github/workflows/base.yml
    with:
      package-name: ' '
  app-1:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: app-1
      storybook: true
      lcov: true
  eslint-config-react:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      namespace: '@fieryeagle'
      package-name: eslint-config-react
      lcov: true
  measure-hook:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: measure-hook
      lcov: true
      build: false
  finish:
    needs: [app-1,eslint-config-react,measure-hook]
    if: ${{ always() }}
    # runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x]
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "app-1,eslint-config-react,measure-hook"
    continue-on-error: true